---
title: "Practicum I CS5200"
authors: "Rupert Simpson, Paula Bass Werner"
date: "Summer Full 2023"
output: html_notebook
---

## Connect to Database

```{r ConnectToDatabase, eval = T, warning = F}
library(RMySQL)

host <- "sql9.freemysqlhosting.net"
username <- "sql9629158"
password <- "bXbHzkNEwi"
dbname <- "sql9629158"

dbcon <- dbConnect(
  MySQL(),
  user = username,
  password = password,
  dbname = dbname,
  host = host
)
```

## Create Database

```{sql CreateAirportsTable, connection=dbcon}
CREATE TABLE IF NOT EXISTS airports (
  aid INT PRIMARY KEY AUTO_INCREMENT,
  airportState TEXT,
  airportCode TEXT
);
```

```{sql CreateFlightTable, connection=dbcon}
CREATE TABLE IF NOT EXISTS flights (
  fid INT PRIMARY KEY,
  date DATE,
  origin INT,
  airline TEXT,
  aircraft TEXT,
  altitude INT,
  heavy BOOLEAN,
  FOREIGN KEY (origin) REFERENCES airports(aid)
);
```

```{sql CreateConditionsTable, connection=dbcon}
CREATE TABLE IF NOT EXISTS conditions (
  cid INT PRIMARY KEY,
  sky_condition TEXT,
  explanation TEXT
);
```

```{sql CreateStrikesTable, connection=dbcon}
CREATE TABLE IF NOT EXISTS strikes (
  sid INT PRIMARY KEY AUTO_INCREMENT,
  fid INT,
  numbirds INT,
  impact TEXT,
  damage BOOLEAN,
  altitude INT CHECK (altitude >= 0),
  conditions INT,
  FOREIGN KEY (conditions) REFERENCES conditions(cid),
  FOREIGN KEY (fid) REFERENCES flights(fid)
);
```

## Manually Test Inserting Into Tables

```{sql airportsTableInsertTest, connection=dbcon, eval=F}
INSERT INTO airports (airportState, airportCode)
VALUES ('California', 'LAX');
```

```{sql airportsTableOutputTest, connection=dbcon, eval=F}
SELECT * FROM airports;
```

```{sql flightsTableInsertTest, connection=dbcon, eval=F}
INSERT INTO flights (fid, date, origin, airline, aircraft, altitude, heavy)
VALUES (1, '2023-06-21', 1, 'Delta', 'Boeing 737', 35000, 1);
```

```{sql flightsTableOutputTest, connection=dbcon, eval=F}
SELECT * FROM flights;
```

```{sql conditionsTableInsertTest, connection=dbcon, eval=F}
INSERT INTO conditions (cid, sky_condition, explanation)
VALUES (1, 'Clear', 'No clouds in the sky.');
```

```{sql conditionsTableOutputTest, connection=dbcon, eval=F}
SELECT * FROM conditions;
```

```{sql strikesTableInsertTest, connection=dbcon, eval=F}
INSERT INTO strikes (fid, numbirds, impact, damage, altitude, conditions)
VALUES (1, 2, 'Engine failure', true, 30000, 1);
```

```{sql strikesTableOutputTest, connection=dbcon, eval=F}
SELECT * FROM strikes;
```

## Clean Data in Preparation for 

```{sql strikesTableReset, connection=dbcon, eval=T}
DELETE FROM strikes;
```

```{sql flightsTableReset, connection=dbcon, eval=T}
DELETE FROM flights;
```

```{sql airportsTableReset, connection=dbcon, eval=T}
DELETE FROM airports;
```

```{sql conditionsTableReset, connection=dbcon, eval=T}
DELETE FROM conditions;
```

```{sql connection=dbcon, eval=T}
ALTER TABLE airports AUTO_INCREMENT = 1;
```

```{sql strikesPrimaryKeyReset, connection=dbcon, eval=T}
ALTER TABLE strikes AUTO_INCREMENT = 1;
```

## Create Dataframe

```{r CreateDataframe, eval = T, warning = F}
bds.raw <- read.csv('BirdStrikesData.csv')

csvData <- head(bds.raw, 100)
```

```{r populateAirportsTable, eval = T, warning = F}
for (row in 1:nrow(datasubset)) {
  # airports table information
  airportState <- csvData[row, "origin"]
  
  # flights table information
  rid <- csvData[row, "rid"]
  date_string <- csvData[row, "flight_date"]
  date_object <- strptime(date_string, format = "%m/%d/%Y %H:%M")
  date <- format(date_object, format = "%Y-%m-%d")
  origin <- row
  airline <- csvData[row, "airline"]
  if (airline == "") {
    airline <- "unknown"
  }
  aircraft <- csvData[row, "aircraft"]
  altitude <- as.integer(gsub(",", "", csvData[row, "altitude_ft"]))
  damage <- csvData[row, "damage"]
  heavy <- 0
  if (damage == "Caused damage") {
    heavy <- 1
  }
  
  #strikes table information
  numbirds <- as.integer(csvData[row, "wildlife_struck"])
  impact <- csvData[row, "impact"]
  
  # conditions table information
  sky_condition <- csvData[row, "sky_conditions"]
  
  # Insert row information into airports table
  airports_insert_query <- sprintf("INSERT INTO airports (airportState) VALUES ('%s')", airportState)
  dbExecute(dbcon, airports_insert_query)
  
  # Insert row information into flights table
  flights_insert_query <- sprintf("INSERT INTO flights (fid, date, origin, airline, aircraft, altitude, heavy) 
                                  VALUES (%d, DATE('%s'), %d, '%s', '%s', %d, %d)", rid, date, origin, airline, aircraft, altitude, heavy)
  dbExecute(dbcon, flights_insert_query)
  
  # Insert row information into conditions table
  conditions_insert_query <- sprintf("INSERT INTO conditions (cid, sky_condition) VALUES (%d, '%s')", rid, sky_condition)
  dbExecute(dbcon, conditions_insert_query)
  
  # Insert row information into strikes table
  strikes_insert_query <- sprintf("INSERT INTO strikes (fid, numbirds, impact, damage, altitude, conditions) 
                                  VALUES (%d, %d, '%s', %d, %d, %d)", rid, numbirds, impact, heavy, altitude, rid)
  dbExecute(dbcon, strikes_insert_query)
}
```

```{sql testStrikesData, connection=dbcon, eval=T}
SELECT * FROM strikes;
```

```{sql testFlightsData, connection=dbcon, eval=T}
SELECT * FROM flights;
```

```{sql testAirportsData, connection=dbcon, eval=T}
SELECT * FROM airports;
```

```{sql testConditionsData, connection=dbcon, eval=T}
SELECT * FROM conditions;
```

## Query For Question 8

```{sql question8, connection=dbcon, eval=T}
SELECT airportState AS state, COUNT(*) AS incidents
FROM strikes
JOIN flights ON strikes.fid = flights.fid
JOIN airports ON flights.origin = airports.aid
GROUP BY airportState
ORDER BY incidents DESC
LIMIT 10;
```

## Query For Question 9

```{sql question9, connection=dbcon, eval=T}
SELECT airline, COUNT(*) AS incidents
FROM strikes
JOIN flights ON strikes.fid = flights.fid
JOIN airports ON flights.origin = airports.aid
GROUP BY airline
HAVING incidents > (SELECT AVG(incident_count) FROM (SELECT COUNT(*) AS incident_count FROM strikes JOIN flights ON strikes.fid = flights.fid GROUP BY airline) AS avg_counts)
ORDER BY incidents DESC;
```

## Query For Question 10

```{r question10, eval = T, warning = F}
library(DBI)

query <- "SELECT DATE_FORMAT(date, '%Y-%m') AS month, SUM(numbirds) AS total_birds
  FROM strikes
  JOIN flights ON strikes.fid = flights.fid
  GROUP BY month
  ORDER BY month;"

result <- dbGetQuery(dbcon, query)

df <- as.data.frame(result)

head(df, 6)
```

## Data Graph For Question 11

```{r question11, eval = T, warning = F}
# Create a column chart
barplot(df$total_birds, names.arg = df$month, xlab = "Month", ylab = "Number of Birds",
        main = "Bird Strikes per Month", col = "blue", ylim = c(0, max(df$total_birds)))

# Add data labels
text(x = 1:length(df$total_birds), y = df$total_birds, labels = df$total_birds, pos = 3, cex = 0.8)

# Add a legend
legend("topright", legend = c("Number of Birds"), fill = "blue")

# Adjust the plot margins
par(mar = c(5, 4, 4, 2) + 0.1)
```

## Stored Procedure for Question 12

```{r question12, eval = T, warning = F}

```

## Disconnect From Database

```{r}
dbDisconnect(dbcon)
```